name: install nodejs and pnpm
description: 'Install nodejs and pnpm environment'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  pnpm-version:
    required: false
    description: pnpm major version
    default: '8'
  node-version:
    required: false
    description: nodejs version
    default: lts/gallium
  token:
    description: github token
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Install pnpm dependencies
      run: pnpm install -r --frozen-lockfile --strict-peer-dependencies
      shell: sh
      env:
        GITHUB_TOKEN: ${{ inputs.token }}